### ISSUE TITLE
Git stash

### ISSUE THREAD

**Issue by IronGremlin** [oliviaguest/git-and-github-cheat-sheet#1]
That's not quite what git stash does.

I mean, it does that, but also it records the current state of your changes in the stash. If you run git stash multiple times, you'll actually put a bunch of different stuff into the stash.

So if someone used git stash to do this, without knowing what git stash is actually for, they'd end up with a ton of garbage in their stash that would make manipu

**Comment by IronGremlin** [comment]
Crap, sorry, on mobile. Anyway, there are cons to using git stash for this, probably better to suggest using reset

**Comment by oliviaguest** [comment]
No, it's fine and even recommended. Have a look at the docs that I linked to in this Tweet: https://twitter.com/o_guest/status/926809828793581569

**Comment by IronGremlin** [comment]
Am I misunderstanding you, or the docs?

The way I read the docs, the workflow I see is to use git stash to stow changes, apply some other change to the project directory, and then use pop to reapply the stash.

The workflow as I read it in your description described simply tossing the changes, which as I understand the docs, would be git stash, and then git stash drop, or clean.

Is there something I'm getting wrong here?

**Comment by oliviaguest** [comment]
You're fine. Newbies don't need to know this much. Also if they use stash it's a lot safer than actually deleting stuff. Either way given you're worried about tons of garbage: https://stackoverflow.com/questions/26190837/how-many-how-long-are-stashes-saved-by-git

**Comment by reitzig** [comment]
I agree with @IronGremlin: the docs _don't_ say "use stash to throw away changes". The scenario is very explicit about the use case being to temporarily store a change set somewhere *and then re-apply it*.

"If you made some local changes and you do not want them around at all", `git reset --hard` is what you want. It's not safe, that much is true.

I'm not decided whether it makes sense to tell newbies to use `git stash` instead. On one hand, it's safer (but only of there's an angelic creature who comes in to save the day, since you don't tell them how to access stashed changes); on the other hand, it teaches them a half-truth that may confuse them if/when they dig deeper into Git.

**Comment by oliviaguest** [comment]
The angelic creature, although I disagree with the description,  is me, since I'm in the same lab. Feel free to teach your newbies differently.

**Comment by drj11** [comment]
The docs, `man git stash`, say

> Use git stash when you want to record the current state of the working
       directory and the index, but want to go back to a clean working
       directory.

So the docs very much support the idea that you can use `git stash` to _go back to a clean working directory_.

However, I _do_ think the text "This discards all your local changes that" is misleading.
Because the changes are in fact kept, stashed away, not discarded.

I think it would be better to:
- emphasise that we are returning to a _clean working directory_; and,
- note that the changes are in fact stored somewhere, and you can borrow an expert to get them back.

I do think it is slightly unusual to advise people to use `git stash` in this way, but it works and is completely fine.
If you do it a lot, you will end up with a lot of (probably useless) stashes, but that tends to only annoy people who like a clean and tidy `git stash list`.
When a novice is ready to worry about the tidyness of the stash list, they are probably ready to tidy it.

**Comment by oliviaguest** [comment]
@drj11 I agree it can be clearer in the [now blogpost](http://neuroplausible.com/github). I suppose I could amend it and add the bit about asking an expert/Stack Overflow, but I'm off to teach another newbie some git funnily enough. :+1:

**Comment by drj11** [comment]
I actually disagree that it could be clearer. The current wording is admirably clear. It's just misleading on one count and wrong on another (now I've discovered what `git add thing` `git stash` does). The reason I struggled with proposing new words was that any other formulation I could come up with was less clear.

**Comment by oliviaguest** [comment]
I'm confused, but you're saying it's fine, so OK. 😅

**Comment by IronGremlin** [comment]
@oliviaguest Sorry to kick off this crazy debate! 

I had no idea `git stash` cleaned up after itself -

With that in mind, this makes a lot more sense as basic newb advice.

Thanks for the knowledge!

**Comment by oliviaguest** [comment]
Ha! No worries. :+1:
